# Site settings
title: "Cartoons By JAY"
email: "wwwlogodesigner@gmail.com"
description: > "Hi, I’m Akash – Cartoon Mascot Logo Designer
I create custom cartoon mascot logos that make your brand unforgettable. My designs are bold, colorful, and full of personality—perfect for businesses that want to stand out and connect with their audience. Whether it’s for a startup, e-sports team, or product branding, I deliver high-quality, original mascot logos that get noticed."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://akashnaveenjay.github.io/logo.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: "akashnaveenjay"

# Build settings
markdown: kramdown
